config/routes.rb
Minifb::Application.routes.draw do
  get "profiles/show"

  devise_for :users

  devise_scope :user do
   get "register", :to  => "devise/registrations#new", as: :register
   get "sign_in", :to  => "devise/sessions#new", as: :sign_in
   get "logout", :to  => "devise/sessions#destroy", as: :logout
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  get 'hello', to: 'statuses#hello', as: :hello
  get 'var', to: 'statuses#var', as: :var
  get 'arr', to: 'statuses#arr', as: :arr
  get 'func', to: 'statuses#func', as: :func
  get 'oandc', to: 'statuses#oandc', as: :oandc
  get 'compile', to: 'statuses#compile', as: :compile
  get 'quiz', to: 'statuses#quiz', as: :quiz
  get 'dis', to: 'statuses#dis', as: :dis

  root :to => 'statuses#index'

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user 

  validates :content, presence: true,
  					  length: {minimum: 2}

  validates :user_id, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true, uniqueness: true
  validates_format_of :profile_name, :with => /^[a-zA-Z0-9_-]+$/, message: 'Must be formatted correctly'



  has_many :statuses
  
  def full_name
  	first_name + " " + last_name
  end

  def gravatar_url
    stripped_email=email.strip
    downcased_email=stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

     "http://gravatar.com/avatar/#{hash}"
      
  
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
       	render file: 'public/404', status: 404, formats: [:html]
    end

  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  # GET /statuses
  # GET /statuses.json

  def index

    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			" "
		end
	end	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EduApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand"> EduApp </a>
				<ul class="nav">
					<li> <%=link_to "Home", feed_path %>
					</li>
				</ul>
				<ul class="nav pull-right">
				<% if user_signed_in? %>
					<li><%=link_to current_user.full_name, edit_user_registration_path %></li>
					<li> <%= link_to "Logout", logout_path %></li> 

					<% else %>
					<li> <%= link_to "Register", register_path %>
						<li> <%= link_to "Login", sign_in_path %>
				 <% end%>


				</ul>
			</div>
		</div>
	</div>
	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%=flash_class type %>">
					<button class="close" data-dismiss="alert">x</button>
					<%= message %>
			</div>
		<%end %>
		

		

<%= yield %>
 </div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h2><%= @user.full_name %></h2>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class ="well">
		<%= status.content %>
		<hr/>
		<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
	</div>
	<%end%>
	<%end%>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.input :user_id, collection: User.all, label_method: :full_name%>
  
 <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/_list.html.erb
<li> <%=link_to "Hello, World!", hello_path %></li>
<li> <%=link_to "Variables and Types", var_path %></li>
<li> <%=link_to "Arrays", arr_path %></li>
<li> <%=link_to "Functions", func_path %></li>
<li> <%=link_to "Objects", oandc_path %></li>
<li> <%=link_to "Compiling and Running with Arguments", compile_path %></li>
<p>
<li> <%=link_to "Quiz", quiz_path %></li>
</p>
<p>
<li> <%=link_to "Discussion forum" , dis_path %></li>
</p>

app/views/statuses/arr.html.erb
<h1>Arrays</h1>
Arrays in Java are also objects. They need to be declared and then created. In order to declare a variable that will hold an array of integers, we use the following syntax:

<pre>int[] arr;</pre>
Notice there is no size, since we didn't create the array yet.

<pre>arr = new int[10];</pre>
This will create a new array with the size of 10. We can check the size by printing the array's length:

<pre>System.out.println(arr.length);</pre>
We can access the array:
<pre>
arr[0] = 4;
arr[1] = arr[0] + 5;
</pre>
We can also create an array with values in the same line:
<pre>
int[] arr = {1, 2, 3, 4, 5};</pre>
Don't try to print the array without a loop, it will print something nasty like [I@f7e6a96.<br>


<br>

<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>

app/views/statuses/compile.html.erb
<h1>Compiling and Running with Arguments</h1>
This section is used for you to use Java at home and understand the basics of how things are done.

After creating a simple application that prints something to the screen, you need to compile your code an run it.
<br>
It shouldn't really matter if you use Linux, Mac or Windows. You need to have a console and you need to have the following commands available in order to compile and run Java.

<ul>

<li>java (or java.exe)</li>
<li>javac (or javac.exe)</li>

</ul>
In order for those to be available you must download and install JDK (Java Development Kit).
<br>
If we take the code from the previous lesson and put it in a file called MyFirstClass.java, in order to compile it we need to run:

<pre>javac MyFirstClass.java</pre>
This is create a file called MyFirstClass.class that holds the compiled java code.

To run it, we need to run java with the name of the class as the argument (Not the file!)

<b></b>Wrong</b>

<pre>java MyFirstClass.class</pre>
Right!

<pre>java MyFirstClass</pre>

<h4>Arguments</h4>
The main methods get an array of strings as an argument, these are the command line arguments you may pass to your program.

Every array in java holds a variable called length that says how many elements are within that array.

We can go over the arguments with a simple for

<pre>public class Arguments {
public static void main(String[] args) {
for (int i = 0; i < args.length; i++) {
System.out.println(args[i]);
}
}
}    </pre>
And o run it with arguments:

<pre>javac Arguments.java
java Arguments arg0 arg1 arg2</pre>  <br>      <br>

<br>

<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>

app/views/statuses/dis.html.erb
<div class="page-header">
  <h1> Discussion forum </h1>
</div>
<%= link_to "Post a new message", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
    <div class="status">
      <div class="row">
        <div class="span1">
          <%= image_tag status.user.gravatar_url %>
        </div>
        <div class="span7">
          <strong><%=status.user.full_name %> </strong>
          <p> <%= status.content %> </p>
          <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + "  ago |", status %>
            <span class="admin">
      <%= link_to "Edit", edit_status_path(status) %> |
              <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you wanna delete"} %>
      </span>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/func.html.erb
<h1>Functions</h1>
In Java, all function definitions must inside classes. We also call functions methods. Let's look at an example method

<pre>public class Main {
public static void foo() {
// Do something here
}
}</pre>
foo is a method we defined in class Main. Notice a few things about foo.
<ul>
<li>static means this method belongs to the class Main and not to a specific instance of Main. Which means we can call the method from a different class like that Main.foo().</li>
<li>void means this method doesn't return a value. Methods can return a single value in Java and it has to be defined in the method declaration.</li>
<li>This method doesn't get any arguments, but of coarse Java methods can get arguments as we'll see further on.</li>
</ul>
<h4>Arguments</h4>
I always like to say that arguments to Java methods are passed by value, although some might disagree with my choice of words, I find it the best way to explain and understand how it works exactly.

By value means that arguments are copied when the method runs. Let's look at an example.

<pre>public void bar(int num1, int num2) {
...
}</pre>
Here is a another place in the code, where bar is called

<pre>int a = 3;
int b = 5;
bar(a, b);</pre>
You can picture in your head that when bar(a, b) is run, it's like in the beginning of bar the following two lines are written:

<pre>int num1 = a;
int num2 = b;</pre>
And only then the rest of the method is run.

This means that a value get copied to num1 and b value get copied to num2. Changing the values of num1 and num2 will not affect a and b.

If the arguments were objects, the rules remain the same, but it acts a bit differently. Here is a an example:

<pre>public void bar2(Student s1, Student s2) {
...
}</pre>
And here is how we use it

<pre>Student joe = new Student("joe");
Student jack = new Student("jack");
bar2(joe, jack);</pre>
Again we can picture the same two lines in the beginning of bar2

<pre>Student s1 = joe;
Student s2 = jack;</pre>
But when we assign objects, it's a bit different than assigning primitives. s1 and joe are two different references to the same object. s1 == joe is true. This means that running methods on s1 will change the object joe. But if we'll change the value of s1 as a reference, it will not affect the reference joe.

<pre>s1.setName("Chuck"); // joe name is now Chuck as well
s1 = new Student("Norris"); // s1 is a new student, different than joe with the name of Norris
// s1 == joe   is not true anymore</pre>
<h4>Non static methods</h4>
Non static methods in Java are used more than static methods. Those methods can only be run on objects and not on the whole class.

Non static methods can access and alter the field of the object.

<pre>public class Student {
private String name;
public String getName() {
return name;
}
public void setName(String name) {
this.name = name;
}
}</pre>
Calling the methods will require an object of type Student.

<pre>Student s = new Student();
s.setName("Danielle");
String name = s.getName();

Student.setName("Bob"); // Will not work!
Student.getName(); // Will not work!</pre>
<h3>Summary</h3>
Every Java method has to be within a class<br>
Static methods belong to a class while non-static methods belong to objects<br>
All parameters to functions are passed by value, primitives content is copied, while objects are not copied and some would say 'passed by reference'<br>

<br>

<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>

app/views/statuses/hello.html.erb
<h1>Hello, World!</h1>

Java is an object oriented language (OOP). Objects in Java are called "classes".

Let's go over the Hello world program, which simply prints "Hello, World!" to the screen.
<pre>
public class Main {
public static void main(String[] args) {
System.out.println("Hello, World!");
}
}
</pre>
The first line defines a class called <code>Main.</code>

<pre>public class Main {</pre>
In Java, every line of code that can actually run needs to be inside a class. This line declares a class named <code>Main</code>, which is <code>public</code>, that means that any other class can access it. This is not important for now, so don't worry. For now, we'll just write our code in a class called Main, and talk about objects later on.

Notice that when we declare a public class, we must declare it inside a file with the same name (Main.java), otherwise we'll get an error when compiling.

When running the examples on the site, we will not use the public keyword, since we write all our code in one file.

The next line is:

<pre>public static void main(String[] args) {</pre>
This is the entry point of our Java program. the main method has to have this exact signature in order to be able to run our program.

<code>public</code> again means that anyone can access it.
<code>static</code> means that you can run this method without creating an instance of Main.
<code>void</code> means that this method doesn't return any value.
<code>main</code> is the name of the method.
The arguments we get inside the method are the arguments that we will get when running the program with parameters. It's an array of strings. We will use it in our next lesson, so don't worry if you don't understand it all now.

<pre>System.out.println("Hello, World!");</pre>
<code>System</code> is a pre-defined class that Java provides us and it holds some useful methods and variables.
<code>out</code> is a static variable within System that represents the output of your program (stdout).
<code>println</code> is a method of out that can be used to print a line.<br>


<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>

app/views/statuses/index.html.erb
<div class="page-header">
<h1> Course Catalogue </h1>
<h4> A platform for beginners to get started with programming</h4>
</div>
<body>
Welcome to the LearnJavaOnline.org Interactive Java Tutorial.

Whether you are an experienced programmer or not, this website is intended for everyone who wishes to learn the Java programming language.

Just click on the chapter you wish to begin from, and follow the instructions. Good luck!

Follow the link below !
</body>



<%= render 'list' %>

app/views/statuses/new.html.erb
<h1>New status</h1>


<%= render 'form' %>


<%= link_to 'Back', statuses_path %>

app/views/statuses/oandc.html.erb
<h1>Objects</h1>
Everything in Java is within classes and objects. Java objects hold a state, state are variables which are saved together within an object, we call them fields or member variables.

Let start with an example:

<pre>class Point {
int x;
int y;
}</pre>
This class defined a point with x and y values.

In order to create an instance of this class, we need to use the keyword new.

<pre>Point p = new Point();</pre>
In this case, we used a default constructor (constructor that doesn't get arguments) to create a Point. All classes that doesn't explicitly define a constructor has a default constructor that does nothing.

We can define our own constructor:

<pre>class Point {
int x;
int y;
Point(int x, int y) {
this.x = x;
this.y = y;
}</pre>
This means we can not longer use the default constructor new Point(). we can now only use the defined constructor new Point(4, 1).

We can define more than one constructor, so Point can be created in several ways. Let's define the default constructor again.

<pre>class Point {
int x;
int y;
Point() {
this(0, 0);
}
Point(int x, int y) {
this.x = x;
this.y = y;
}</pre>
Notice the usage of the this keyword here. We can use in within a constructor to call a different constructor (in order to avoid code duplication). It can only be the first line within the constructor.

We also used the this keyword as a reference of the current object we are running on.

After we defined p we can access x and y.

<pre>p.x = 3;
p.y = 6;</pre>

<h4>Methods</h4>
We can now define methods on Point.

<pre>class Point {
... // Our code previously
void printPoint() {
System.out.println("(" + x + "," + y + ")");
}
Point center(Point other) {
// Returns the center between this point the other point
// Notice we are using integer, we wan't get an accurate value
return new Point((x + other.x) / 2, (y + other.y) / 2);
}</pre>

<h4>Public and Private</h4>
Although we'll talk about modifiers later on, it's important to understand the different between private and public variables and methods.

When using the keyword private before a variable or a method, it means only the class itself can access the variable or method, when we're using public it means everybody can access it. We usually see constructors defined as public, variables defined as private and methods are separated, some public and some private.<br>

<br>

<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>

app/views/statuses/quiz.html.erb
<h2> Test Yourself </h2>
<br>
<br>
<p>
  <b>1. Object oriented programming means :</b>
</p>
<ol>
  <li> Designing the application based on the objects discovered when analysing the problem </li>
  <li>Writing an algorithm before writing your program and having a test plan </li>
  <li>Writing a program composed of Java classes </li>
  <li> Being objective about what you develop </li>
</ol>
<br>
<p>
  <b>2. Which is not a part of defining an object? </b>
</p>
<ol>
  <li> Description </li>
  <li>Methods </li>
  <li>Associations with other objects </li>
  <li> Name </li>
</ol>
<p><b>3. Every comparison operator in java will return the type: </b>
</p>
<ol>
  <li> Boolean  </li>
  <li>Integer </li>
  <li> Double</li>
  <li> String</li>
</ol>

<p>
  <b>4. What displays from the following statements? String word = "abcde"; for (int i = 0; i <4; i+=2) System.out.print(word[i]);</b>
</p>
<ol>
  <li>ab  </li>
  <li>ace</li>
  <li> bd</li>
  <li> ac</li>
</ol>

<p>
  <b> 5. When we are using objects and want to check if they are equal, _____ wiil say if they are the same, if you want to check if they are logically equal, you should use the ________ on the object.</b>
</p>
<ol>
  <li> ===, equals method </li>
  <li>==, ===</li>
  <li> equals method, ==</li>
  <li> ==, equals method</li>
</ol>
<p>


<p>
  <b> 6. _______ means this method belongs to the class Main and not to a specific instance of Main.</b>
</p>

<p>
  <b>7. We can define more than 1 constructor </b>
</p>
<ol>
  <li> True </li>
  <li> False </li>
</ol>
<p>
  <b> 8. When using the keyword __________ before a variable or a method, it means only the class itself can access the variable or method, when we're using _________ it means everybody can access it.</b>
</p>
<ol>
  <li> Public,Protected </li>
  <li> Public, Private </li>
  <li> Protected, Public </li>
  <li> Private, Public </li>
</ol>


<b> 9. In order to compile a java code we use _______ followed by <filename>.java, in order to run it, we use _______ followed by <filename></b>
</p>
<ol>
  <li>javac,java </li>
  <li> java, javac </li>
  <li> compile, run </li>
  <li> jcompile, jrun </li>
</ol>
<p>
  <b> 10. Given the declaration : int [ ] ar = {1,2,3,4,5}; What is the value of ar[4]?</b>
</p>
<ol>
  <li> 2 </li>
  <li> 3 </li>
  <li> 4 </li>
  <li> 5 </li>
</ol>

app/views/statuses/show.html.erb
<p>
  <b>Name:</b>
  <%=@status.user.full_name %> 
  
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/var.html.erb
<h1>Variables and Types</h1>
Although Java is object oriented, not all types are objects. It is built on top of basic variable types called primitives.
<p>
Here is a list of all primitives in Java:</p>
<ul>
<li>byte (number, 1 byte)</li>
<li>short (number, 2 bytes)</li>
<li>int (number, 4 bytes)</li>
<li>long (number, 8 bytes)</li>
<li>float (float number, 4 bytes)</li>
<li>double (float number, 8 bytes)</li>
<li>char (a character, 2 bytes)</li>
<li>boolean (true or false, 1 byte)</li>
</ul>
Java is a strong typed language, which means variables need to be defined before we use them.
<h4>
Numbers</h4>
To declare and assign a number use the following syntax:
<pre>
int myNumber;
myNumber = 5;
</pre>
Or you can combine them:
<pre>
int myNumber = 5;
</pre>
To define a floating point number, use the following syntax:
<pre>
double d = 4.5;
d = 3;
</pre>
If you want to use float, you will have to cast:

<pre>float f = (float) 4.5;</pre>
<h4>Characters and Strings</h4>
In Java, a character is it's own type and it's not simply a number, so it's not common to put an ascii value in it, there is a special syntax for chars:

<pre>char c = 'g';</pre>
String is not a primitive. It's a real type, but Java has special treatment for String.

Here are some ways to use a string:
<pre>
// Create a string with a constructor
String s1 = new String("Who let the dogs out?");
// Just using "" creates a string, so no need to write it the previous way.
String s2 = "Who who who who!";
// Java defined the operator + on strings
String s3 = s1 + s2;
</pre>
There is no operator overloading in Java! The operator + is only defined for strings, you will never see it with other objects, only primitives.

You can also concat string to primitives:
<pre>
int num = 5;
String s = "I have " + num + " cookies";
</pre>
<h4>boolean</h4>
Every comparison operator in java will return the type boolean that not like other languages can only accept two special values: true or false.
<pre>
boolean b = false;
b = true;

boolean toBe = false;
b = toBe || !toBe;
if (b) {
System.out.println(toBe);
}

int children = 0;
b = children; // Will not work
if (children) { // Will not work
// Will not work
}
</pre>
<br>

<br>

<p><h3><%= link_to 'Back', statuses_path %>       </h3> </p>